### ISSUE TITLE
关于数据储存处理的一些建议

### ISSUE THREAD

**Issue by panpaul** [Undefined01/FASQS#1]
1、鉴于不是所有成绩都在校网上有，部分成绩需要手动导入，我觉得应该考虑一下程序自己的数据库，在每次运行时同步校网上的数据，同时也支持自己导入的其他数据。（这点在todo里有）
2、由于实际原因，不是每周都考完所有科目，在汇总排名时要增添跨周排名的功能。
3、生态园的DJ会定期删除列表中时间较早的周（如：第一周），但这部分数据依然在服务器上可以查询，我觉得可以做一个循环（从第一周到第n周）或是手动输入的功能。

**Comment by Undefined01** [comment]
1. 没有可靠的数据源。
目前就数学校数据库上的成绩最有统计意义
像是数学的系列训练，一没有可靠的数据源，统计总分和小分没有意义；二没有可比性，其他班也没有考试，FY的PPT里的数据已经足够了。
2. 这种大周测会统一出现在“第一轮周测”和“第二轮周测”等考试中
暂时还没有写灵活的跨考试查询系统，但是只要前端选好了科目，后端根据API来组合数据也不是什么难事。
3. 这种数据可以手动调整，可以考虑统一到优化程序阶段再完成。

**Comment by panpaul** [comment]
关于第一点：对于排名，xw主要关注的是我们自己，平时周测，自己跟自己比。对于数学化学，多数周测是不会登记到校网上的，需要从老师那里获取。

**Comment by Undefined01** [comment]
如果要涉及到个人纵向比较的话，那么确实应该需要一个数据库。
但是既然涉及到数据库，那么就要考虑到用什么数据库的问题。
如果采用大型数据库的话，windows下（特别是有还原）会让整个系统非常难受。
目前我正在完善前端横向比较的部分，其他我还没有想到那么远。

**Comment by panpaul** [comment]
额，其实我想表达的是班级内部比较（48人的排名）。不过既然提到了个人纵向比较，也不失为一个好想法。
关于数据库，我觉得可以用sqlite做轻量级储存。

**Comment by Undefined01** [comment]
sqlite感觉干这种事情不是很灵活，毕竟表的结构都是写死的，而且可用的分级就那么多。
如果考试的科目不太一致（如有时科目只有几个），那么表的结构就会有点难以维护。
至少我没有想到什么好方法。

**Comment by panpaul** [comment]
#3  我觉得可以用type+subject的方法记录，另外对于学校一次产生约1200*6的数据，sqlite是hold的住的，我猜测学校的系统也是这么做的。
