### ISSUE TITLE
关于持久化储存的一些想法

### ISSUE THREAD

**Issue by panpaul** [Undefined01/FASQS#3]
数据结构：

 sid | name | class | type | subject | objectivepoint | subjectivepoint | classrank | graderank
 --- | ---- | ----- | ---- | ------- | -------------- | --------------- | --------- | ---------
16XXXX | XXX | XXX | 第一周 | math | 60 | 90 | 1 | 1

关于总分，我觉得可以获取的时候手动加一下（以免出现101分的现象）

我觉得持久化储存暂且可分为以下几块：
- [ ] 一层wrapper（提供接口）
- [ ] 数据同步（从校网）
- [ ] 数据导入（可能要写层pharser）
- [ ] 数据呈现（读取）

**Comment by panpaul** [comment]
在爬取部分与数据持久化储存方面所用的对于单个学生的数据所用的struct应该统一

**Comment by Undefined01** [comment]
emmm，说的现实一点，我感觉我们的项目好像撑不到那么久。
爬取部分的输出结构确实不是很合理，但是为了迎合学校数据库，只能这样了。
其实我现在正在补充一个“拆解再打包”这些数据的API。
看看还有没有更高的需求再说吧。
PS：我感觉等到我的这个打包API写完，就可以开写导出到Excel的那一部分了。

**Comment by panpaul** [comment]
因为第2号是pull uprequest #2
