### ISSUE TITLE
不建议将ci build提交到git上

### ISSUE THREAD

**Issue by panpaul** [Undefined01/FASQS#5]
考虑到国内q的feature，clone速度极慢。

**Comment by Undefined01** [comment]
emmmm，其实你可以不用管build分支的。
`git clone -b master https://github.com/Undefined01/FASQS`就好了。
至于CI上怎么用LFS……
好吧，其实也没什么，就是懒而已。

**Comment by panpaul** [comment]
好的好的，我知道了.
